#### EDA FOR WORKOUT REPORTS

In [1]:
# importing libaries
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
df=pd.read_csv("D:\gitfit-tracker\Workout Report\workout_report.csv")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:1: SyntaxWarning: invalid escape sequence '\g'
C:\Users\tsaja\AppData\Local\Temp\ipykernel_8496\1331197323.py:1: SyntaxWarning: invalid escape sequence '\g'
  df=pd.read_csv("D:\gitfit-tracker\Workout Report\workout_report.csv")

      Workout Name  Reps  Set  Time  Rest Time
0  Standard PushUp     0    1  0:43        0.0
1  Standard PushUp     1    1  0:49        0.0
2  Standard PushUp     2    1   2:5        0.0
3  Standard PushUp     3    1   2:7        0.0
4  Standard PushUp     4    1  2:10        0.0

In [5]:
df.sort_index(ascending=False)

       Workout Name  Reps  Set  Time  Rest Time
17  Standard PushUp     4    2  3:40  45.006175
16  Standard PushUp     3    2  3:38  45.006175
15  Standard PushUp     2    2  3:34  45.006175
14  Standard PushUp     1    2  3:32  45.006175
13  Standard PushUp     0    2  3:17  45.006175
12             REST    12    1  2:32   0.000000
11  Standard PushUp    11    1  2:29   0.000000
10  Standard PushUp    10    1  2:25   0.000000
9   Standard PushUp     9    1  2:22   0.000000
8   Standard PushUp     8    1  2:20   0.000000
7   Standard PushUp     7    1  2:17   0.000000
6   Standard PushUp     6    1  2:15   0.000000
5   Standard PushUp     5    1  2:13   0.000000
4   Standard PushUp     4    1  2:10   0.000000
3   Standard PushUp     3    1   2:7   0.000000
2   Standard PushUp     2    1   2:5   0.000000
1   Standard PushUp     1    1  0:49   0.000000
0   Standard PushUp     0    1  0:43   0.000000

In [5]:
plt.barh(df["Workout Name"].value_counts)

TypeError: barh() missing 1 required positional argument: 'width'